import Navbar from '@/components/Navbar';
import { LayoutProps } from '@/types/common';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import ThemeProvider from '@/components/ThemeProvider';
import { Box } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, ...rest }: LayoutProps) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
